POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arthur Lavault",
    "number": "079-904-01-72"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "079-904-01-72"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arthur Lavault"
}


###
GET http://localhost:3001/api/persons